sudo: false

language: dart
dart:
  - dev

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

before_script:
  - nvm install 8.13.0
  - nvm use 8.13.0
  - node --version
  - npm install
  - npm install -g firebase-tools
  - ./tool/deploy.sh
  - source /home/travis/google-cloud-sdk/path.bash.inc # Add gcloud to $PATH

script:

  - pub run test -p node -j 1 -r expanded
